- job_name: 'node-exporter'
  metrics_path: '/metrics'
  static_configs:
    - targets: ['44.208.34.159:9100']

- job_name: blackbox
  metrics_path: /probe
  params:
    module: [http_2xx]
  static_configs:
    - targets:
        - http://44.208.34.159/events
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    replacement: prometheus-blackbox-exporter.monitoring:9115